// Các dịch vụ AI miễn phí dùng qua website chính thức.
// Không cần API key và không được xem là kết nối API thật.
// Bambuseae chỉ mở đúng trang chính thức; hạn mức do từng nhà cung cấp quản lý.
const models = [
  {
    id: "chatgpt-free-web",
    name: "ChatGPT Free",
    provider: "OpenAI",
    category: "Đa năng",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiConnectorId: "openai-personal",
    apiUrl: "https://platform.openai.com/api-keys",
    apiLabel: "Lấy API OpenAI chính thức ↗",
    apiNote: "Để dùng trong Bambuseae, cần OpenAI API key riêng. Gói ChatGPT Free trên web không tự bao gồm quota API.",
    available: true,
    webUrl: "https://chatgpt.com/",
    status: "Mở web chính thức",
    reset: "Theo hạn mức ChatGPT",
    note: "Dùng miễn phí qua ChatGPT; hạn mức và tính năng có thể thay đổi."
  },
  {
    id: "gemini-free-web",
    name: "Gemini Free",
    provider: "Google",
    category: "Đa phương thức",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiConnectorId: "gemini-personal",
    apiUrl: "https://aistudio.google.com/app/apikey",
    apiLabel: "Lấy API Gemini chính thức ↗",
    apiNote: "Để dùng trong Bambuseae, cần Gemini API key riêng. Hạn mức API được Google quản lý tách khỏi Gemini web.",
    available: true,
    webUrl: "https://gemini.google.com/",
    status: "Mở web chính thức",
    reset: "Theo hạn mức Gemini",
    note: "Dùng miễn phí qua Gemini; hạn mức phụ thuộc model, tính năng và nhu cầu hệ thống."
  },
  {
    id: "claude-free-web",
    name: "Claude Free",
    provider: "Anthropic",
    category: "Viết & phân tích",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiConnectorId: "claude-personal",
    apiUrl: "https://console.anthropic.com/settings/keys",
    apiLabel: "Lấy API Anthropic chính thức ↗",
    apiNote: "Để dùng trong Bambuseae, cần Anthropic API key riêng. Tài khoản Claude web không tự truyền sang API.",
    available: true,
    webUrl: "https://claude.ai/",
    status: "Mở web chính thức",
    reset: "Theo hạn mức Claude",
    note: "Gói miễn phí của Claude; dung lượng sử dụng có giới hạn."
  },
  {
    id: "copilot-free-web",
    name: "Microsoft Copilot Free",
    provider: "Microsoft",
    category: "Đa năng & tìm kiếm",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiUrl: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/",
    apiLabel: "Xem tài liệu Microsoft AI ↗",
    apiNote: "Copilot consumer trên web không cung cấp API key tương đương. Có thể dùng Azure/OpenAI hoặc Copilot Studio connector riêng.",
    available: true,
    webUrl: "https://copilot.microsoft.com/",
    status: "Mở web chính thức",
    reset: "Theo chính sách Copilot",
    note: "Có thể dùng miễn phí; giới hạn phụ thuộc tính năng, tài khoản và hệ thống."
  },
  {
    id: "grok-free-web",
    name: "Grok Free",
    provider: "xAI",
    category: "Đa năng & thời gian thực",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiConnectorId: "grok",
    apiUrl: "https://console.x.ai/",
    apiLabel: "Lấy API xAI chính thức ↗",
    apiNote: "Để dùng trong Bambuseae, cần xAI API key riêng. Hạn mức Grok web không phải quota API.",
    available: true,
    webUrl: "https://grok.com/",
    status: "Mở web chính thức",
    reset: "Theo hạn mức Grok",
    note: "Grok có thể dùng miễn phí trong hạn mức; gói trả phí có hạn mức cao hơn."
  },
  {
    id: "deepseek-free-web",
    name: "DeepSeek Free",
    provider: "DeepSeek",
    category: "Suy luận & code",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiConnectorId: "deepseek",
    apiUrl: "https://platform.deepseek.com/api_keys",
    apiLabel: "Lấy API DeepSeek chính thức ↗",
    apiNote: "Để dùng trong Bambuseae, cần DeepSeek API key riêng; tài khoản web và API là hai luồng hạn mức khác nhau.",
    available: true,
    webUrl: "https://chat.deepseek.com/",
    status: "Mở web chính thức",
    reset: "Theo chính sách DeepSeek",
    note: "Ứng dụng/web được công bố miễn phí; giới hạn phục vụ có thể thay đổi theo tải hệ thống."
  },
  {
    id: "qwen-free-web",
    name: "Qwen Studio Free",
    provider: "Alibaba / Qwen",
    category: "Đa năng & mã nguồn mở",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiConnectorId: "qwen",
    apiUrl: "https://dashscope.console.aliyun.com/apiKey",
    apiLabel: "Lấy API Qwen/DashScope chính thức ↗",
    apiNote: "Qwen Studio web không tự cấp quyền API cho Bambuseae; cần DashScope key và endpoint model tương ứng.",
    available: true,
    webUrl: "https://chat.qwen.ai/",
    status: "Mở web chính thức",
    reset: "Theo chính sách Qwen",
    note: "Qwen Studio mở cho người dùng; hạn mức có thể phụ thuộc tài khoản và khu vực."
  },
  {
    id: "meta-ai-free-web",
    name: "Meta AI Free",
    provider: "Meta",
    category: "Đa năng & hình ảnh",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiUrl: "https://www.llama.com/",
    apiLabel: "Xem tài liệu Llama chính thức ↗",
    apiNote: "Meta AI consumer trên web không có API key tương đương. Có thể kết nối Llama qua endpoint hosted hoặc máy chủ riêng.",
    available: true,
    webUrl: "https://www.meta.ai/",
    status: "Mở web chính thức",
    reset: "Theo hạn mức Meta AI",
    note: "Trợ lý Meta AI miễn phí; một số tính năng nặng có hạn mức ngày/tháng."
  },
  {
    id: "perplexity-free-web",
    name: "Perplexity Free",
    provider: "Perplexity",
    category: "Tìm kiếm & nghiên cứu",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiConnectorId: "perplexity",
    apiUrl: "https://www.perplexity.ai/settings/api",
    apiLabel: "Lấy API Perplexity chính thức ↗",
    apiNote: "Để dùng trong Bambuseae, cần Perplexity API key riêng; quota web không tự chuyển sang API.",
    available: true,
    webUrl: "https://www.perplexity.ai/",
    status: "Mở web chính thức",
    reset: "Theo hạn mức Perplexity",
    note: "Gói miễn phí có tìm kiếm cơ bản, Pro Search và tải file trong hạn mức."
  },
  {
    id: "le-chat-free-web",
    name: "Le Chat Free",
    provider: "Mistral AI",
    category: "Đa năng & code",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiConnectorId: "mistral",
    apiUrl: "https://console.mistral.ai/api-keys/",
    apiLabel: "Lấy API Mistral chính thức ↗",
    apiNote: "Le Chat web và Mistral API có tài khoản/quota riêng; cần Mistral API key để chạy trong Bambuseae.",
    available: true,
    webUrl: "https://chat.mistral.ai/",
    status: "Mở web chính thức",
    reset: "Theo hạn mức Le Chat",
    note: "Gói Free có giới hạn theo ngày/tính năng."
  },
  {
    id: "poe-free-web",
    name: "Poe Free",
    provider: "Poe",
    category: "Nhiều bot AI",
    tier: "Miễn phí qua web",
    webOnly: true,
    apiUrl: "https://developer.poe.com/",
    apiLabel: "Xem tài liệu Poe dành cho developer ↗",
    apiNote: "Poe web không tự cấp một API key dùng chung cho mọi bot. Chỉ kết nối được khi bạn có endpoint/API chính thức phù hợp.",
    available: true,
    webUrl: "https://poe.com/",
    status: "Mở web chính thức",
    reset: "Điểm làm mới mỗi 24 giờ",
    note: "Tài khoản miễn phí nhận điểm dùng hằng ngày; bot khác nhau có mức tiêu hao khác nhau."
  }
];

export default models;
